permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::295793222430:role/github-actions-oidc-practice
          aws-region: us-west-2
      - run: |
          Install-Module -Name AWS.Tools.EC2 -Force
          Get-EC2Vpc
        shell: pwsh
