on:
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:
          aws-secret-access-key:
          aws-region: us-east-2
